CI: upgrade .NET from 5.0.100 to 5.0.202 to fix macOS build
There was an intermittent build issue on macOS, which seems related to:
https://github.com/NuGet/Home/issues/10491#issuecomment-819122398

The (intermittent) errors of the macOS build were:

* Step 'Restore tools':

warning NU3028: Package 'Fornax 0.13.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
error NU3037: Package 'Fornax 0.13.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
warning NU3028: Package 'fake-cli 5.20.4-alpha.1642' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
error NU3037: Package 'fake-cli 5.20.4-alpha.1642' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
warning NU3028: Package 'dotnet-fsharplint 0.16.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
error NU3037: Package 'dotnet-fsharplint 0.16.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
warning NU3028: Package 'Paket 5.252.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
error NU3037: Package 'Paket 5.252.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.

Package "fake-cli" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
Package "paket" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
Package "dotnet-fsharplint" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
Package "fornax" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)

Restore failed.
Error: Process completed with exit code 1.

* Step 'Run build':
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.Console.Tests/bin/Release/net5.0/FSharpLint.Console.Tests.dll (net5.0)
Finished (Success) 'DotNet:test' in 00:00:11.1338241
Starting task 'DotNet:restore': tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln
/Users/runner/work/FSharpLint/FSharpLint> "/Users/runner/.dotnet/dotnet"  restore tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln /clp:ForceConsoleColor /bl:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpoIYOVJ.tmp.binlog (In: false, Out: false, Err: false)
/Users/runner/.dotnet/sdk/5.0.100/MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/runner/.dotnet/sdk/5.0.100/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/runner/.dotnet/sdk/5.0.100/dotnet.dll -maxcpucount -target:Restore -verbosity:m /bl:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpoIYOVJ.tmp.binlog /clp:ForceConsoleColor tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln
  Determining projects to restore...
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj : error NU3028: Package 'Microsoft.NETCore.Platforms 1.1.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj : error NU3037: Package 'Microsoft.NETCore.Platforms 1.1.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj : error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj : error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj : error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj : error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired. [/Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.sln]
  Failed to restore /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj (in 663 ms).
  Failed to restore /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj (in 663 ms).
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj(0,0): error NU3028: Package 'Microsoft.NETCore.Platforms 1.1.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj(0,0): error NU3037: Package 'Microsoft.NETCore.Platforms 1.1.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj(0,0): error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj(0,0): error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj(0,0): error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj(0,0): error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj(0,0): error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj(0,0): error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj(0,0): error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
RestoreTask: /Users/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj(0,0): error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.8' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired.
Finished (Failed) 'DotNet:restore' in 00:00:02.1316696
Finished (Failed) 'Test' in 00:01:40.7375376

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.0059468
Build      00:00:31.4180335
Test       00:01:40.7373066   (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
Total:     00:02:12.2927884
Status:    Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Test' failed.
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Hint: Could not find a version in your paket.dependencies file, consider adding 'version 5.257.0' at the top of your dependencies file (/Users/runner/work/FSharpLint/FSharpLint/paket.dependencies).
Read fsharp/FAKE#2193 for details.