.config/dotnet-tools.json: upd paket 5.252.0 to 7.2.1
With `dotnet tool update paket --version 7.2.1`; because the previous
CI's err message was:

```
Run dotnet fake build -t Build
Extracted Paket.Restore.targets to: /home/runner/work/FSharpLint/FSharpLint/.paket/Paket.Restore.targets (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)
There was a problem while setting up the environment:
-> Extracting platforms from path 'net6.0' failed, a newer Paket version might support it, otherwise please open an issue for a missing platform handler.
Hint: If you just upgraded the fake-runner you can try to remove the .fake directory and try again.
Error: Process completed with exit code 1.
```