CI,.config: go back to old version of Fornax
The latest version of Fornax is also throwing exceptions, albeit
different than the previously reported ones (so we go back to the
old version, having to install old .NETCore3.x for now):

```
System.TypeLoadException: Could not load type 'FSharp.Compiler.SourceCodeServices.FSharpAssembly' from assembly 'FSharp.Compiler.Service, Version=41.0.7.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at FSharp.MetadataFormat.MetadataFormat.Generate(IEnumerable`1 dllFiles, FSharpOption`1 parameters, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 markDownComments, FSharpOption`1 urlRangeHighlight)
   at FSharp.MetadataFormat.MetadataFormat.Generate(String dllFile, FSharpOption`1 parameters, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 markDownComments, FSharpOption`1 urlRangeHighlight) in /app/src/FSharp.MetadataFormat/Main.fs:line 1506
   at FSI_0004.Apirefloader.loader(String projectRoot, SiteContents siteContet) in D:\a\FSharpLint\FSharpLint\docs\loaders\apirefloader.fsx:line 41
[12:16:29] multiple files generated in 570ms
[12:16:29] 'D:\a\FSharpLint\FSharpLint\docs\_public\index.json' generated in 222ms
ERROR IN PAGE GENERATION:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FSI_0025.Menu.menu(SiteContents ctx, String page) in D:\a\FSharpLint\FSharpLint\docs\generators\partials\menu.fsx:line 13
   at FSI_0025.Layout.layout(SiteContents ctx, IEnumerable`1 bodyCnt, String page) in D:\a\FSharpLint\FSharpLint\docs\generators\partials\layout.fsx:line 39
   at FSI_0025.Page.generate'(SiteContents ctx, String page) in D:\a\FSharpLint\FSharpLint\docs\generators\page.fsx:line 12
   at FSI_0025.Page.generate(SiteContents ctx, String projectRoot, String page) in D:\a\FSharpLint\FSharpLint\docs\generators\page.fsx:line 16
[12:16:29] 'D:\a\FSharpLint\FSharpLint\docs\_public\index.html' generated in 318ms
...
```