CI,dotnet-tools: update Fornax again
The recent update[1] to Fornax caused NullReferenceExceptions in the
log (even though CI doesn't break) so we suspect this version might
have some kind of problem. Let's update to the last version (and for
this we've had to update the .NET version of this job, otherwise
the last version of Fornax cannot run with v5.0).

But note that after updating to this version, we've had to do some
other changes related to the .NET upgrade (to v6):

The Directory.Build.props change is to fix this restore error:

```
Run dotnet restore
  dotnet restore
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    DOTNET_VERSION: 5.0.202
    DOTNET_ROOT: C:\Program Files\dotnet
  Determining projects to restore...
Error: C:\Program Files\dotnet\sdk\6.0.417\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(29,5): error NETSDK1138: The target framework 'net5.0' is
out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
[D:\a\FSharpLint\FSharpLint\tests\FSharpLint.FunctionalTest\FSharpLint.FunctionalTest.fsproj]
Error: C:\Program Files\dotnet\sdk\6.0.417\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(29,5): error NETSDK1138: The target framework 'net5.0' is
out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
[D:\a\FSharpLint\FSharpLint\src\FSharpLint.Core\FSharpLint.Core.fsproj]
Error: C:\Program Files\dotnet\sdk\6.0.417\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(29,5): error NETSDK1138: The target framework 'net5.0' is
out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
[D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Core.Tests\FSharpLint.Core.Tests.fsproj]
Error: C:\Program Files\dotnet\sdk\6.0.417\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(29,5): error NETSDK1138: The target framework 'net5.0' is
out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
[D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Console.Tests\FSharpLint.Console.Tests.fsproj]
Error: C:\Program Files\dotnet\sdk\6.0.417\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(29,5): error NETSDK1138: The target framework 'net5.0' is
out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
[D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Benchmarks\FSharpLint.Benchmarks.fsproj]
Error: C:\Program Files\dotnet\sdk\6.0.417\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(29,5): error NETSDK1138: The target framework 'net5.0' is
out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
[D:\a\FSharpLint\FSharpLint\src\FSharpLint.Console\FSharpLint.Console.fsproj]
  Restored D:\a\FSharpLint\FSharpLint\src\FSharpLint.Console\FSharpLint.Console.fsproj (in 6.28 sec).
  Restored D:\a\FSharpLint\FSharpLint\src\FSharpLint.Core\FSharpLint.Core.fsproj (in 6.28 sec).
  Restored D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Console.Tests\FSharpLint.Console.Tests.fsproj (in 6.28 sec).
  Restored D:\a\FSharpLint\FSharpLint\tests\FSharpLint.FunctionalTest\FSharpLint.FunctionalTest.fsproj (in 6.28 sec).
  Restored D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Benchmarks\FSharpLint.Benchmarks.fsproj (in 3 ms).
  Restored D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Core.Tests\FSharpLint.Core.Tests.fsproj (in 3 ms).
Error: Process completed with exit code 1.
```

And the .fs changes are to build these .NET6.0 compilation errors:
```
Error: D:\a\FSharpLint\FSharpLint\src\FSharpLint.Core\Rules\Conventions\RaiseWithTooManyArguments\FailwithBadUsage.fs(122,11): error FS0026: This rule will never be matched
[D:\a\FSharpLint\FSharpLint\src\FSharpLint.Core\FSharpLint.Core.fsproj]

Build FAILED.

Error: D:\a\FSharpLint\FSharpLint\src\FSharpLint.Core\Rules\Conventions\RaiseWithTooManyArguments\FailwithBadUsage.fs(122,11): error FS0026: This rule will never be matched
[D:\a\FSharpLint\FSharpLint\src\FSharpLint.Core\FSharpLint.Core.fsproj]
    0 Warning(s)
    1 Error(s)

Error: D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Core.Tests\Rules\Conventions\CyclomaticComplexity.fs(232,3): error FS0058: Possible incorrect indentation: this token is
offside of context started at position (229:9). Try indenting this token further or using standard formatting conventions.
[D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Core.Tests\FSharpLint.Core.Tests.fsproj]
Error: D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Core.Tests\Rules\Conventions\CyclomaticComplexity.fs(232,3): error FS0058: Possible incorrect indentation: this token is
offside of context started at position (229:9). Try indenting this token further or using standard formatting conventions.
[D:\a\FSharpLint\FSharpLint\tests\FSharpLint.Core.Tests\FSharpLint.Core.Tests.fsproj]
    0 Warning(s)
    2 Error(s)

```

[1] b4da0c87cfa0c24147b04a03e4b2131c20abfb36