paket.dependencies: pin MS.NET.Test.Sdk to higher version
In order to avoid this problem when running the tests:
```
sing "CheckForImplicitPackageReferenceOverrides" task from assembly "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
Task "CheckForImplicitPackageReferenceOverrides"
Done executing task "CheckForImplicitPackageReferenceOverrides".
Done building target "CheckForImplicitPackageReferenceOverrides" in project "FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj".
Target "ApplyImplicitVersions" in file "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.Shared.targets" from project
"/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj" (target
"ProcessFrameworkReferences" depends on it):
Using "ApplyImplicitVersions" task from assembly "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
Task "ApplyImplicitVersions"
Done executing task "ApplyImplicitVersions".
Done building target "ApplyImplicitVersions" in project "FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj".
Target "ProcessFrameworkReferences" in file "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets" from project
"/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj" (target
"ResolvePackageAssets" depends on it):
Using "CheckForDuplicateFrameworkReferences" task from assembly "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
Task "CheckForDuplicateFrameworkReferences"
Done executing task "CheckForDuplicateFrameworkReferences".
Using "ProcessFrameworkReferences" task from assembly "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
Task "ProcessFrameworkReferences"
The "ProcessFrameworkReferences" task failed unexpectedly.
System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.3.3.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
File name: 'NuGet.Frameworks, Version=6.3.3.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.3.3.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Build.Shared.MSBuildLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
Done executing task "ProcessFrameworkReferences" -- FAILED.
```